#!/bin/bash

# Cloudinary Quick Setup Script for Student Hub
# This script helps you set up Cloudinary configuration

echo "🎨 Student Hub - Cloudinary Setup Helper"
echo "========================================"
echo ""

# Check if .env.local exists
if [ ! -f .env.local ]; then
    echo "❌ .env.local file not found!"
    echo "Please create .env.local first with your existing variables"
    exit 1
fi

echo "📋 Follow these steps to complete Cloudinary setup:"
echo ""
echo "1️⃣  Go to https://cloudinary.com/users/register/free"
echo "   - Sign up for a free account"
echo "   - Verify your email"
echo ""
echo "2️⃣  Get your credentials from https://cloudinary.com/console"
echo "   - Cloud Name (e.g., dxxxxx)"
echo "   - API Key"
echo "   - API Secret"
echo ""
echo "3️⃣  Create Upload Presets:"
echo "   Go to Settings → Upload → Upload presets"
echo ""
echo "   📦 Product Images Preset:"
echo "      - Name: student-hub-products"
echo "      - Signing Mode: Unsigned ⚠️ IMPORTANT"
echo "      - Folder: student-hub/products"
echo "      - Transformations: Width 800, Height 800, Crop Fill"
echo ""
echo "   🎥 Video Stories Preset:"
echo "      - Name: student-hub-stories"
echo "      - Signing Mode: Unsigned ⚠️ IMPORTANT"
echo "      - Folder: student-hub/stories"
echo "      - Resource Type: Video"
echo "      - Transformations: Width 1080, Height 1920"
echo ""
echo "   👤 Avatars Preset:"
echo "      - Name: student-hub-avatars"
echo "      - Signing Mode: Unsigned ⚠️ IMPORTANT"
echo "      - Folder: student-hub/avatars"
echo "      - Transformations: Width 200, Height 200, Crop Fill, Radius Max"
echo ""
echo "4️⃣  Add these variables to your .env.local:"
echo ""
echo "# Cloudinary Configuration"
echo "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=your_cloud_name_here"
echo "NEXT_PUBLIC_CLOUDINARY_API_KEY=your_api_key_here"
echo "CLOUDINARY_API_SECRET=your_api_secret_here"
echo "NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET_PRODUCTS=student-hub-products"
echo "NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET_STORIES=student-hub-stories"
echo "NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET_AVATARS=student-hub-avatars"
echo ""
echo "5️⃣  Restart your dev server:"
echo "   npm run dev"
echo ""
echo "6️⃣  Test the upload:"
echo "   - Go to http://localhost:3000/products/new"
echo "   - Click 'Upload Product Image'"
echo "   - Select an image from your device"
echo "   - Check Cloudinary dashboard to see it in student-hub/products/"
echo ""
echo "✅ Once complete, you'll have:"
echo "   - Organized media folders"
echo "   - Automatic image optimization"
echo "   - CDN delivery worldwide"
echo "   - 25GB free storage + 25GB bandwidth/month"
echo ""
echo "📚 For detailed instructions, see CLOUDINARY_SETUP.md"
echo ""
